# Generated by Django 6.0.3 on 2026-03-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('images_to_pdf', 'Images → PDF'), ('pdf_to_images', 'PDF → Images'), ('compress', 'Compress PDF'), ('merge', 'Merge PDFs'), ('split', 'Split PDF'), ('rotate', 'Rotate PDF'), ('extract_text', 'Extract Text'), ('watermark', 'Add Watermark')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
